variables: 
  TEST_NAME:  registry.gitlab.com/vahe.chobanyan12/sverige:$CI_COMMIT_REF_NAME

stages: 
  - build
  - deploy
build_docker_image:
   stage: build 
   script: 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $TEST_NAME .
    - docker push $TEST_NAME
   tags:
    - build
run_docker_image:
   stage : deploy
   script:
     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
     - docker pull $TEST_NAME
     - docker kill $(docker ps -q) || true 
     - docker rm   $(docker ps -q) || true
     - docker run -d -p 7575:8000 $TEST_NAME

   tags:
     - run
